name: newsapp
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  dio: ^5.4.0
  flutter_svg: ^2.0.9
  jiffy: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  mockito: ^5.4.4
  mock_data: ^2.0.1
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/svg/app/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf

    - family: IbmPlexSerif
      fonts:
        - asset: assets/fonts/IBMPlexSerif-Bold.ttf
        - asset: assets/fonts/IBMPlexSerif-BoldItalic.ttf
        - asset: assets/fonts/IBMPlexSerif-ExtraLight.ttf
        - asset: assets/fonts/IBMPlexSerif-ExtraLightItalic.ttf
        - asset: assets/fonts/IBMPlexSerif-Italic.ttf
        - asset: assets/fonts/IBMPlexSerif-Light.ttf
        - asset: assets/fonts/IBMPlexSerif-LightItalic.ttf
        - asset: assets/fonts/IBMPlexSerif-Medium.ttf
        - asset: assets/fonts/IBMPlexSerif-MediumItalic.ttf
        - asset: assets/fonts/IBMPlexSerif-Regular.ttf
        - asset: assets/fonts/IBMPlexSerif-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSerif-SemiBoldItalic.ttf
        - asset: assets/fonts/IBMPlexSerif-Thin.ttf
        - asset: assets/fonts/IBMPlexSerif-ThinItalic.ttf
